<a href="https://colab.research.google.com/github/joulongleu/BANanoWebix/blob/master/%E3%80%8Cu1_benchmark_crawler_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 爬取大盤

本課成為「[用Python打造AI股票理專](https://hahow.in/cr/finlab-ml)」的第一堂課！

由於這是進階課程，所以會講的比較快，假如這堂課的速度你可以跟上，之後的課程一定也沒問題！

FinLab提供的爬蟲可以爬取股價、月報財報、三大法人、殖利率等等

但你一定會希望能夠擴增資料庫，讓它更豐富、更實用！

所以這個單元，跟我們一起實做一個「加權指數爬蟲」吧！

* 下方是課程影片可以直接免費觀看
* 往下拉是範例，方便您線上學習和執行代碼！

In [ ]:
# 呼叫影片的代碼，不要亂修改，不然影片會不見喔！可以播放影片，並且往下拉去玩玩看更多程式碼！

from IPython.display import HTML

# Youtube
HTML("""
<iframe  width="560" height="315"  src="https://www.youtube.com/embed/4Ym07B15N0Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
""")

### 爬蟲的網址

我們想要爬取的網址如下：
http://www.tse.com.tw/zh/page/trading/exchange/MI_5MINS_INDEX.html

### 下載某天的資料

In [ ]:
# 如何線上玩程式？
#
# 1. 點選左上角「用PLAYGROUND模式打開」
# 2. 點選此代碼區塊，然後點選左方的「三角形」開始跑程式！（遇到警告直接按「仍然運行」即可）

import requests

res = requests.get("http://www.twse.com.tw/exchangeReport/MI_5MINS_INDEX?response=csv&date=20190102&_=1552616075051")
res.text[:1000]

'"108年01月02日每5秒指數統計"\r\n"時間","發行量加權股價指數","未含金融保險股指數","未含電子股指數","未含金融電子股指數","水泥類指數","食品類指數","塑膠類指數","紡織纖維類指數","電機機械類指數","電器電纜類指數","化學生技醫療類指數","化學類指數","生技醫療類指數","玻璃陶瓷類指數","造紙類指數","鋼鐵類指數","橡膠類指數","汽車類指數","電子類指數","半導體類指數","電腦及週邊設備類指數","光電類指數","通信網路類指數","電子零組件類指數","電子通路類指數","資訊服務類指數","其他電子類指數","建材營造類指數","航運類指數","觀光類指數","金融保險類指數","貿易百貨類指數","油電燃氣類指數","其他類指數",\r\n="09:00:00","9,727.41","8,145.71","13,851.88","11,683.21","129.81","1,617.70","277.92","505.99","158.99","46.43","91.30","101.94","55.27","34.80","181.71","104.72","242.57","198.27","388.00","151.06","82.61","32.62","122.64","84.80","107.19","91.21","70.82","259.73","64.38","101.40","1,187.56","241.61","138.19","233.55",\r\n="09:00:05","9,725.27","8,143.83","13,835.69","11,664.40","130.10","1,610.65","275.85","506.02","158.99","46.43","91.34","101.94","55.34","34.80","181.74","104.55","242.87","198.27","388.25","151.64","82.79","32.66","120.14","85.09","107.19","91.39","71.20","259.73","64.38","101.41","1,187.38","241.61","138.19","233.98",\r'

### 將資料用pandas整理成表格(dataframe)

Pandas 教學：
http://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

In [ ]:
import pandas as pd
import io
df = pd.read_csv(io.StringIO(res.text.replace("=", "")), header=1, index_col='時間')
df.head()

         發行量加權股價指數 未含金融保險股指數    未含電子股指數  ... 油電燃氣類指數   其他類指數 Unnamed: 35
時間                                       ...
09:00:00  9,727.41  8,145.71  13,851.88  ...  138.19  233.55         NaN
09:00:05  9,725.27  8,143.83  13,835.69  ...  138.19  233.98         NaN
09:00:10  9,730.34  8,147.35  13,845.10  ...  138.19  234.18         NaN
09:00:15  9,724.78  8,142.20  13,835.07  ...  136.40  234.61         NaN
09:00:20  9,730.49  8,147.77  13,845.49  ...  137.00  234.62         NaN

[5 rows x 35 columns]

### 資料處理
1. 去除不需要的行、列
2. 設定index為日期
3. 將逗點「,」刪除，讓table裡面的字串(str)變成數字(float or int)

In [ ]:
df = df.dropna(how='all', axis=0).dropna(how='all', axis=1)
df.index = pd.to_datetime(datestr + ' ' + df.index)
df = df.applymap(lambda s: float(str(s).replace(",", "")))
df.head()

NameError: ignored

### 全部加在一起

In [ ]:
# 時間物件
import datetime

# 下載網頁用的
import requests

# 資料處理
import pandas as pd

# 檔案串流
from io import StringIO


# 下載某天的資料

date = datetime.date(2018,1,3)
date_str = date.strftime('%Y%m%d')
res = requests.get("http://www.twse.com.tw/exchangeReport/MI_5MINS_INDEX?response=csv&date=" + 
                   date_str + "&_=1544020420045")

# 利用 pandas 將資料整理成表格

df = pd.read_csv(StringIO(res.text.replace("=","")), header=1, index_col='時間')

# 資料處理

df = df.dropna(how='all', axis=0).dropna(how='all', axis=1)
df.index = pd.to_datetime(date.strftime('%Y %m %d ') + pd.Series(df.index))
df = df.apply(lambda s: s.astype(str).str.replace(",", "").astype(float))

df.head()

,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,電器電纜類指數,...,電子通路類指數,資訊服務類指數,其他電子類指數,建材營造類指數,航運類指數,觀光類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,其他類指數
時間,,,,,,,,,,,,,,,,,,,,,
2018-01-03 09:00:00,10710.73,9094.86,14537.98,12469.76,118.30,1650.04,284.81,491.68,195.92,52.67,...,120.67,88.49,101.61,261.65,69.72,134.95,1196.45,238.23,145.33,253.80
2018-01-03 09:00:05,10759.61,9139.70,14553.75,12478.29,118.30,1650.11,285.31,491.65,195.94,53.14,...,120.67,88.51,101.61,261.65,69.97,134.95,1198.94,238.23,145.33,253.80
2018-01-03 09:00:10,10765.54,9144.68,14564.15,12487.82,118.35,1650.11,285.54,492.46,196.11,53.18,...,120.67,88.51,101.86,261.81,70.09,134.95,1199.65,238.23,145.33,253.88
2018-01-03 09:00:15,10775.89,9155.36,14575.94,12504.18,118.35,1648.79,285.58,492.26,196.49,53.18,...,120.79,88.52,101.92,261.95,70.10,134.95,1199.13,239.05,146.53,254.06
2018-01-03 09:00:20,10777.92,9157.53,14577.97,12507.33,118.35,1649.48,285.51,492.88,196.75,53.15,...,120.86,88.51,101.94,262.05,70.13,134.95,1198.96,239.09,146.53,254.09

### 有了這個功能後，下一步呢？

下一步我們要將這個資料整合進資料庫喔！

讓資料庫變成超級豐富吧！

可以到「[用Python打造AI股票理專](https://hahow.in/cr/finlab-ml)」來參考AI選股課程喔！